# Generated by Django 5.1.15 on 2026-08-25 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto'),
        ),
        migrations.AddConstraint(
            model_name='permissaomodulo',
            constraint=models.UniqueConstraint(fields=('papel', 'modulo'), name='uniq_permissao_papel_modulo'),
        ),
        migrations.AddField(
            model_name='setor',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setor',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='core.setor'),
        ),
        migrations.AddField(
            model_name='user',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.setor'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['objeto_tipo', 'objeto_id', '-quando'], name='core_audito_objeto__ccf377_idx'),
        ),
    ]
