# Generated by Django 5.1.15 on 2026-08-25 12:45

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('fase', models.CharField(choices=[('ideia', 'Ideia'), ('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('fila', 'Na fila'), ('desenvolvimento', 'Em desenvolvimento'), ('testes', 'Em testes'), ('homologacao', 'Homologação'), ('implantacao', 'Implantação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ideia', max_length=16)),
                ('horas_estimadas', models.PositiveIntegerField(default=0)),
                ('inicio_previsto', models.DateField(blank=True, null=True)),
                ('fim_previsto', models.DateField(blank=True, null=True)),
                ('encerrado_em', models.DateField(blank=True, null=True)),
                ('situacao_final', models.CharField(blank=True, max_length=180)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_patrocinados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('setor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='core.setor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('previsto', models.DateField()),
                ('concluido_em', models.DateField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.PositiveSmallIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='projetos.projeto')),
            ],
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nome'], name='projeto_nome_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fase__in', ['concluido', 'cancelado']), _negated=True), ('encerrado_em__isnull', False), _connector='OR'), name='proj_encerrado_tem_data'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.CheckConstraint(condition=models.Q(('percentual__lte', 100)), name='aloc_percentual_max_100'),
        ),
    ]
