# Generated by Django 5.1.15 on 2026-08-25 12:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaReposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=14)),
                ('minimo', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origem', models.CharField(choices=[('minimo', 'Saldo no mínimo'), ('transferencia', 'Transferência furou mínimo')], max_length=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContagemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sistema', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_contado', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('prazo_resposta', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('respondida', 'Respondida'), ('fechada', 'Fechada')], default='aberta', max_length=12)),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=8)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('divergencias', models.PositiveIntegerField(default=0)),
                ('impacto_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'verbose_name': 'inventário',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=180)),
                ('unidade', models.CharField(max_length=8)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('codigo_sankhya', models.CharField(blank=True, db_index=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('divergencia', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transf_saida', 'Transferência (saída)'), ('transf_entrada', 'Transferência (entrada)'), ('ajuste', 'Ajuste de inventário')], max_length=14)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('sinal', models.SmallIntegerField(default=1)),
                ('saldo_apos', models.DecimalField(decimal_places=3, max_digits=14)),
                ('os_ref', models.CharField(blank=True, max_length=30)),
                ('justificativa', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(blank=True, max_length=6)),
                ('fornecedor', models.CharField(max_length=140)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='notas/%Y/%m/')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['-emissao'],
            },
        ),
        migrations.CreateModel(
            name='PropostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=140)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prazo_entrega_dias', models.PositiveSmallIntegerField()),
                ('escolhida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=14, unique=True)),
                ('os_ref', models.CharField(blank=True, max_length=30)),
                ('urgente', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aprovada', 'Aprovada'), ('atendida', 'Atendida'), ('negada', 'Negada')], default='aberta', max_length=10)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_negacao', models.CharField(blank=True, max_length=240)),
                ('origem', models.CharField(choices=[('sistema', 'Sistema'), ('whatsapp', 'WhatsApp')], default='sistema', max_length=12)),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(max_length=180)),
                ('fura_minimo_origem', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'transferência',
                'verbose_name_plural': 'transferências',
                'ordering': ['-criado_em'],
            },
        ),
    ]
