# Generated by Django 5.1.15 on 2026-08-25 12:45

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('chamados', '0001_initial'),
        ('core', '0003_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertareposicao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estoque',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.setor'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.setor'),
        ),
        migrations.AddField(
            model_name='contageminventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='almoxarifado.inventario'),
        ),
        migrations.AddField(
            model_name='item',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='setor_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.setor'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='contageminventario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='alertareposicao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='itemsolicitacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.centrocusto'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.inventario'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.setor'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='conferida_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.setor'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.notafiscal'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.notafiscal'),
        ),
        migrations.AddField(
            model_name='propostacotacao',
            name='cotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='almoxarifado.cotacao'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='centro_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.centrocusto'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.setor'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimento',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.solicitacao'),
        ),
        migrations.AddField(
            model_name='itemsolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.solicitacao'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.item'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='setor_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transf_entradas', to='core.setor'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transf_saidas', to='core.setor'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.transferencia'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberto')), fields=('setor',), name='inv_um_aberto_por_setor'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['descricao'], name='item_descricao_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('item', 'setor'), name='uniq_estoque_item_setor'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='estoque_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contageminventario',
            constraint=models.UniqueConstraint(fields=('inventario', 'item'), name='uniq_contagem_item'),
        ),
        migrations.AddConstraint(
            model_name='contageminventario',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_contado__isnull', True), ('saldo_contado__gte', 0), _connector='OR'), name='contagem_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='alertareposicao',
            constraint=models.UniqueConstraint(condition=models.Q(('resolvido_em__isnull', True)), fields=('item', 'setor'), name='uniq_alerta_aberto'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('numero', 'serie', 'cnpj'), name='uniq_nf'),
        ),
        migrations.AddConstraint(
            model_name='propostacotacao',
            constraint=models.UniqueConstraint(condition=models.Q(('escolhida', True)), fields=('cotacao',), name='uniq_proposta_escolhida'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'item'), name='uniq_item_solicitacao'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='itemsol_qtd_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_atendida__lte', models.F('quantidade'))), name='itemsol_atendida_lte_pedida'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('setor_origem', models.F('setor_destino')), _negated=True), name='transf_setores_diferentes'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='transf_qtd_positiva'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['item', '-criado_em'], name='almoxarifad_item_id_2936ca_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['setor', 'tipo', '-criado_em'], name='almoxarifad_setor_i_86c628_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['centro_custo'], name='almoxarifad_centro__b44732_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='mov_qtd_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('sinal__in', [1, -1])), name='mov_sinal_valido'),
        ),
    ]
