# Generated by Django 5.1.15 on 2026-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='chamados/%Y/%m/')),
                ('nome_original', models.CharField(max_length=180)),
                ('tamanho_bytes', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('exige_documentacao', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=12, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=10)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('triagem', 'Em triagem'), ('fila', 'Na fila'), ('execucao', 'Em execução'), ('testes', 'Em testes'), ('aguarda', 'Aguardando solicitante'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='novo', max_length=12)),
                ('horas_previstas_min', models.PositiveIntegerField(default=0)),
                ('sla_previsto', models.DateTimeField(blank=True, null=True)),
                ('sla_cumprido', models.BooleanField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('interno', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(max_length=240)),
            ],
            options={
                'ordering': ['quando'],
            },
        ),
        migrations.CreateModel(
            name='RegraSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=10)),
                ('horas_uteis', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'regra de SLA',
                'verbose_name_plural': 'regras de SLA',
            },
        ),
    ]
