# Generated by Django 5.1.15 on 2026-08-25 12:45

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0001_initial'),
        ('core', '0003_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.categoria'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_abertos', to='core.setor'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexo',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regrasla',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_sla', to='chamados.categoria'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['status', 'responsavel'], name='chamados_ch_status_37a7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['setor_origem', 'status'], name='chamados_ch_setor_o_2ac2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['sla_previsto'], name='chamados_ch_sla_pre_123e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titulo'], name='chamado_titulo_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='regrasla',
            constraint=models.UniqueConstraint(fields=('categoria', 'prioridade'), name='uniq_sla_cat_prio'),
        ),
    ]
