# Generated by Django 5.1.15 on 2026-08-25 12:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('chave_hash', models.CharField(editable=False, max_length=64)),
                ('prefixo_chave', models.CharField(editable=False, max_length=8)),
                ('escopos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('ips_permitidos', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=list, size=None)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_tecnico', models.ForeignKey(help_text='Ações feitas por este sistema são registradas em nome deste usuário.', on_delete=django.db.models.deletion.PROTECT, related_name='sistemas_externos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sistema externo',
                'verbose_name_plural': 'sistemas externos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('segredo', models.CharField(help_text='HMAC-SHA256 do corpo no header X-Assinatura', max_length=64)),
                ('eventos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=list, size=None)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integracoes.sistemaexterno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=60)),
                ('carga', models.JSONField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('falhou', 'Falhou')], db_index=True, default='pendente', max_length=10)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('proxima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.CharField(blank=True, max_length=240)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.auditoria')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='integracoes.webhook')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChaveIdempotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=128)),
                ('caminho', models.CharField(max_length=200)),
                ('status_http', models.PositiveSmallIntegerField()),
                ('resposta', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracoes.sistemaexterno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sistema', 'chave'), name='uniq_idempotencia')],
            },
        ),
    ]
