# Generated by Django 5.1.15 on 2026-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_exige_causa', models.BooleanField(default=False, editable=False)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=240)),
                ('detalhe_retrabalho', models.CharField(blank=True, max_length=240)),
                ('lancamento_manual', models.BooleanField(default=False)),
                ('pendente_aprovacao', models.BooleanField(db_index=True, default=False)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('recusado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='MotivoRetrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'motivo de retrabalho',
                'verbose_name_plural': 'motivos de retrabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('exige_causa', models.BooleanField(default=False)),
                ('contabiliza_capacidade', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tipo de trabalho',
                'verbose_name_plural': 'tipos de trabalho',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
