# Generated by Django 5.1.15 on 2026-08-25 12:45

import apontamentos.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apontamentos', '0001_initial'),
        ('chamados', '0001_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='motivo_retrabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apontamentos.motivoretrabalho'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apontamentos.tipotrabalho'),
        ),
        migrations.AddIndex(
            model_name='apontamento',
            index=models.Index(fields=['usuario', '-inicio'], name='apontamento_usuario_9c922e_idx'),
        ),
        migrations.AddIndex(
            model_name='apontamento',
            index=models.Index(fields=['tipo'], name='apontamento_tipo_id_811cdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gt', models.F('inicio')), _connector='OR'), name='ap_fim_maior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.CheckConstraint(condition=models.Q(('chamado__isnull', False), ('projeto__isnull', False), _connector='OR'), name='ap_tem_destino'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_exige_causa', False), ('motivo_retrabalho__isnull', False), _connector='OR'), name='ap_retrabalho_tem_causa'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=models.UniqueConstraint(condition=models.Q(('fim__isnull', True)), fields=('usuario',), name='ap_um_cronometro_aberto'),
        ),
        migrations.AddConstraint(
            model_name='apontamento',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(apontamentos.models.TsTzRange('inicio', 'fim', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('usuario', '=')], name='ap_sem_sobreposicao'),
        ),
    ]
