from django.urls import path

from . import views, views_almox, views_compras, views_config, views_projetos

app_name = "web"

urlpatterns = [
    path("", views.tarefas, name="inicio"),
    path("entrar/", views.Entrar.as_view(), name="entrar"),
    path("sair/", views.Sair.as_view(), name="sair"),
    path("tarefas/", views.tarefas, name="tarefas"),
    path("tarefas/novo/", views.abrir_chamado, name="abrir_chamado"),
    path("tarefa/", views.tarefa_atual, name="tarefa_atual"),
    path("tarefas/<int:pk>/", views.tarefa, name="tarefa"),
    path("tarefas/<int:pk>/cronometro/", views.cronometro, name="cronometro"),
    path("tarefas/<int:pk>/lancamento/", views.lancamento_manual, name="lancamento_manual"),
    path("tarefas/<int:pk>/lancamento/previa/", views.previa_manual, name="previa_manual"),
    path("tarefas/<int:pk>/transicao/", views.transicao, name="transicao"),
    path("tarefas/<int:pk>/comentar/", views.comentar, name="comentar"),
    path("tarefas/<int:pk>/documentacao/<slug:secao>/", views.editor_documento, name="editor_documento"),
    path("busca/", views.busca, name="busca"),
    path("cronometro/estado/", views.cronometro_estado, name="cronometro_estado"),
    path("aprovacoes/", views.aprovacoes, name="aprovacoes"),
    path("aprovacoes/decidir/", views.decidir_aprovacoes, name="decidir_aprovacoes"),
    path("painel/", views.painel, name="painel"),
    path("projetos/", views_projetos.projetos, name="projetos"),
    path("projetos/historico/", views_projetos.historico, name="projetos_historico"),
    path("projetos/novo/", views_projetos.novo, name="projeto_novo"),
    path("projetos/<int:pk>/mover/", views_projetos.mover, name="projeto_mover"),
    path("almoxarifado/", views_almox.almoxarifado, name="almoxarifado"),
    path("almoxarifado/itens/", views_almox.itens_busca, name="almox_itens_busca"),
    path("almoxarifado/solicitar/", views_almox.solicitar, name="almox_solicitar"),
    path("almoxarifado/solicitacoes/<int:pk>/<slug:acao>/", views_almox.solicitacao_acao, name="almox_solicitacao_acao"),
    path("almoxarifado/saida/", views_almox.saida_rapida, name="almox_saida"),
    path("almoxarifado/transferir/", views_almox.transferir, name="almox_transferir"),
    path("almoxarifado/transferir/previa/", views_almox.previa_transferencia, name="almox_previa_transferencia"),
    path("almoxarifado/nota/", views_almox.entrada_nota, name="almox_nota"),
    path("almoxarifado/inventario/", views_almox.inventario, name="almox_inventario"),
    path("almoxarifado/qr/", views_almox.qrcode, name="almox_qr"),
    path("almoxarifado/qr/<str:codigo>/", views_almox.qrcode, name="almox_qr_codigo"),
    path("compras/", views_compras.compras, name="compras"),
    path("compras/cotacoes/nova/", views_compras.abrir_cotacao, name="cotacao_nova"),
    path("compras/cotacoes/<int:pk>/proposta/", views_compras.proposta, name="cotacao_proposta"),
    path("compras/propostas/<int:pk>/escolher/", views_compras.escolher, name="proposta_escolher"),
    path("compras/alertas/<int:pk>/resolver/", views_compras.resolver_alerta, name="alerta_resolver"),
    path("config/", views_config.config, name="config"),
    path("config/sla/simular/", views_config.simular_sla, name="config_simular_sla"),
    path("config/sla/", views_config.salvar_sla, name="config_salvar_sla"),
    path("config/permissao/", views_config.alternar_permissao, name="config_permissao"),
    path("config/<slug:modelo>/<int:pk>/<slug:campo>/", views_config.alternar_flag, name="config_flag"),
    path("config/<slug:modelo>/novo/", views_config.novo_cadastro, name="config_novo"),
    path("historico/", views_config.historico_mudancas, name="historico"),
]
